version: '3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: unless-stopped
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: underscores_db
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - ./:/var/www/html
     ports:
       - "8000:80"
     restart: unless-stopped

     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: root

   phpmyadmin:
     depends_on:
       - db
     image: phpmyadmin/phpmyadmin
     ports:
       - "8080:80"
     restart: unless-stopped
     environment:
       PMA_ARBITRARY: 1
       PMA_HOST: db:3306
       MYSQL_ROOT_PASSWORD: root
volumes:
    db_data: